### ISSUE TITLE
Session data too big to fit in a cookie, causes login redirect loop

### ISSUE THREAD

**Issue by agabriel-dpc** [zamzterz/cognito-demo#4]
Please see this issue and its comments for the original problem description and suggestions: https://github.com/zamzterz/Flask-pyoidc/issues/115

@zamzterz is right, the issue belongs to the example code, not the extension.
in searching for the solution  Flask told me to change session storage type.
So I did this in the example code:

`app.config['SESSION_TYPE'] = 'filesystem' `

As I tested this solution still wants to store the whole data in a cookie in the browser, and since the cookie is bigger than 4k, Chrome simply ignores it. 

I suspect the id_token has to be stored in a cookie in the browser anyway because that's how it will be authenticated against any resource protected by Cognito, right?

Could you please help me extending the demo app (or suggesting an alternative solution?)
Thank you!

**Comment by zamzterz** [comment]
Unfortunately I can't help you with that, as this repo only contains a simple example (and not production code).
But you should be on the right track with changing `SESSION_TYPE`, I'm not sure why that wouldn't work.
